name: flutter_archetype
description: A clean architecture Flutter project template ready for production.
publish_to: "none"

version: 1.0.9+2

environment:
  sdk: ">=3.8.6 <4.0.0"

dependencies:
  # Core Flutter packages
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI and icons
  cupertino_icons: ^1.0.8

  # Animations
  flutter_animate: ^4.5.2

  hybrid_calendar:
    path: ../
  intl: ^0.20.2

dev_dependencies:
  # Testing
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
